### ISSUE TITLE
A suggestion for clarity

### ISSUE THREAD

**Issue by FerdinandBeaman** [learn-co-curriculum/dsc-sql-subqueries#2]
## Link to Canvas

https://learning.flatironschool.com/courses/6221/assignments/226345?module_item_id=529074

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x] Other (explain below)

### Source

```

```

### Concern

The examples in the lesson use tables that have columns with the same name as one another, like how officeCode is in both the employees and offices table. But it isn't stated that you can actually run subqueries that reference keys in a table that have a different title, such as employeeNumber in "employees" and its analog salesRepEmployeeNumber in "customers".

## (Optional) Proposed Solution

I feel like this possibility should be at least mentioned somewhere in the lesson. I spent quite a while trying to google an answer for how it would be done before resorting to trial and error.

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by jessepisel** [comment]
Thank you for the suggesion :wave:. I have updated the repo with commit [e99da31](https://github.com/learn-co-curriculum/dsc-sql-subqueries/commit/e99da316be9770d90256a3a409ce2cbc70ca1ce5)
